### ISSUE TITLE
Manifest V2  ->Manifest V3

### ISSUE THREAD

**Issue by bj803** [posebear1990/TwitterWithBaiduTranslator#2]
你好，用了好几个翻译，还是你这个最好用，一直在用，现在按你教程替换了 .env 文件里百度appId，一样很好用！
我的问题是在2023年1月就不能用Manifest V2的扩展了，所以恳请你做个Manifest V3版本的，在此谢谢了！

**Comment by posebear1990** [comment]
感谢支持，已经更新。后面我会提供一个界面来让用户使用自己的 APPID

**Comment by bj803** [comment]
非常感谢！
