### ISSUE TITLE
可以做一个油猴脚本的版本吗

### ISSUE THREAD

**Issue by KervynH** [posebear1990/TwitterWithBaiduTranslator#3]
这样子可以支持大多数手机浏览器了。很多轻量级的浏览器（比如via）不支持扩展，但是支持脚本。

**Comment by posebear1990** [comment]
蛮不错的建议，不过一是手机刷推大部分人直接用客户端了，第二是确实没时间搞这个，用❤️发电理解一下🤣
最后，再次谢谢你的建议
